# Film Technology 2 — Installation on Macs or PCs (Windows/Linux) outside Room 043

Thanks to Anaconda, installing all the necessary packages is very simple. Just download and install the newest Anaconda version for your operating system from the website below. Almost all the packages we'll need (NumPy, Matplotlib, and Jupyter Notebooks) are already included. Only Libraw needs to be installed separately.

1.) Download and intall Anaconda: https://www.anaconda.com/download
2.) 

# Film Technology 2 — Introduction to Python
Author: Prof. Dr Jan Froehlich

We import `numpy` for array math and `matplotlib` for displaying images and plots. You may know these libraries from the 'Informatik 1' and 'Informatik 2' courses.

In [1]:
import numpy as np               # array math
import matplotlib.pyplot as plt  # images and plots
import time                      # needed to measure execution time

---
## Anlegen einer Skalarvariablen
*(Skalar = einzelne Zahl, kein Vektor)*

In Jupyter wird der Wert des letzten Ausdrucks in einer Zelle automatisch angezeigt —
genau wie MATLAB ohne Semikolon.


In [ ]:
# MATLAB: a = 3.14
a = 3.14
a


## Frage: 5 mal — WAS ist 10?


In [ ]:
# MATLAB: 2 * 5
2 * 5


## Semikolon / Ausgabe unterdrücken

In MATLAB unterdrückt `;` die Ausgabe bei einer Zuweisung.
In Python ist **Zuweisung immer still** — nur der letzte Ausdruck ohne Zuweisung wird angezeigt.
Zum expliziten Drucken verwendet man `print()`.


In [ ]:
# MATLAB: c;   <- Strichpunkt unterdrückt Ausgabe
# Python: Zuweisung ist immer still — kein Semikolon nötig
c = 99     # keine Ausgabe
c          # Ausgabe, weil letzter Ausdruck der Zelle


---
## Zeilenvektor anlegen

| | MATLAB | Python / NumPy |
|---|---|---|
| Zeilenvektor | `b = [1, 2, 3]` | `b = np.array([1, 2, 3])` |
| Spaltenvektor | `c = [1; 2; 3]` | `c = np.array([[1],[2],[3]])` |
| Transponieren | `c = b'` | `c = b.reshape(-1, 1)` |


In [ ]:
# MATLAB: b = [1, 2, 3];
b = np.array([1, 2, 3])
print('b       :', b)
print('b.shape :', b.shape)   # (3,) — eindimensionales Array


In [ ]:
# MATLAB: c = [1; 2; 3];
c = np.array([[1],
              [2],
              [3]])
print('c.shape :', c.shape)   # (3,1) — zweidimensionale Spalte


In [ ]:
# MATLAB: c = b'
c = b.reshape(-1, 1)   # -1 bedeutet: Dimension automatisch berechnen
print('transponiert, c.shape :', c.shape)


---
## Matrix anlegen

MATLAB trennt Zeilen mit `;`, Spalten mit Leerzeichen oder `,`.
In NumPy ist jede Zeile eine Python-Liste innerhalb der äußeren Liste.


In [ ]:
# MATLAB: m = [1 2 3; 4 5 6; 7 8 9];
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
m


---
## Zugriff auf einzelne Elemente — Python ist **0-indiziert!**

Das ist der häufigste Fehler beim Wechsel von MATLAB zu Python:

| MATLAB | Python | Wert |
|---|---|---|
| `m(1,3)` | `m[0,2]` | 3 |
| `m(2,1)` | `m[1,0]` | 4 |

Python-Bonus: **negative Indizes** zählen vom Ende — kein `end`-Schlüsselwort nötig.


In [ ]:
# MATLAB: m(1,3)  ->  Python: m[0,2]
print('m[0,2] =', m[0,2])    # Zeile 0, Spalte 2  ->  3
print('m[1,0] =', m[1,0])    # Zeile 1, Spalte 0  ->  4

# Negativer Index: zählt vom Ende  (kein 'end'-Schlüsselwort nötig)
print('m[-1,-1] =', m[-1,-1])  # letzte Zeile, letzte Spalte  ->  9


In [ ]:
# MATLAB: m(1,2) = 17
m[0,1] = 17
print(m)
# Ausgabe:
#  [[ 1 17  3]
#   [ 4  5  6]
#   [ 7  8  9]]


---
## Elementweise Operationen

| MATLAB | Python | Bedeutung |
|---|---|---|
| `m .* m` | `m * m` | elementweise Multiplikation |
| `m .^ 2` | `m ** 2` | elementweises Potenzieren |
| `m * eye(3)` | `m @ np.eye(3)` | **Matrix**multiplikation |

> **Wichtig:** In MATLAB ist `*` Matrixmultiplikation, `.*` elementweise.
> In NumPy ist `*` **elementweise** (Standard!) und `@` ist Matrixmultiplikation.


In [ ]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])  # neu anlegen (17 wieder raus)

# MATLAB: m .* m
print('m * m (elementweise) =')
print(m * m)


In [ ]:
# MATLAB: m .^ 2
print('m ** 2 =')
print(m ** 2)


In [ ]:
# MATLAB: m * eye(3)    <- ohne Punkt = Matrixmultiplikation
# Python: m @ np.eye(3)  <- @ ist der Matrixmultiplikations-Operator
print('m @ np.eye(3) =')
print(m @ np.eye(3))


---
## Wichtige Datentypen in der Bildverarbeitung

| Typ | Wertebereich | Einsatz |
|---|---|---|
| `uint8` | 0 ... 255 | Bilder auf Festplatte (JPEG, PNG) |
| `uint16` | 0 ... 65535 | RAW-Sensordaten |
| `float64` | -inf ... +inf | Alle Berechnungen |

**Achtung:** `uint8` sättigt bei 0 und 255.
In NumPy muss man **`np.clip()` vorher aufrufen**, um das explizit zu machen.


In [ ]:
# MATLAB: e = [-5, 0, 0.49, 0.5, 0.51, 1, 255, 300];
#         e_uint8 = uint8(e);
#         [e; double(e_uint8)]

e = np.array([-5, 0, 0.49, 0.5, 0.51, 1, 255, 300])

e_uint8 = np.clip(e, 0, 255).astype(np.uint8)   # clip zuerst — dann casten!

print('Original float :', e)
print('Als uint8      :', e_uint8.astype(float))
print()
print('Beobachtungen:')
print('  -5   ->  0    (Saettigung nach unten)')
print('  300  ->  255  (Saettigung nach oben)')
print('  0.49 ->  0    (Trunkierung, nicht Rundung!)')


---
## Bilder lesen, anzeigen und schreiben

| MATLAB | Python |
|---|---|
| `imread('peppers.png')` | `plt.imread('peppers.png')` |
| `imshow(img)` | `ax.imshow(img)` + `plt.show()` |
| `imwrite(img,'out.jpg')` | `plt.imsave('out.jpg', img)` |
| `size(img)` | `img.shape` |


In [ ]:
# MATLAB: img = imread('peppers.png');
# Wir laden das klassische peppers-Testbild aus dem Internet.
# Ohne Internet: img = plt.imread('peppers.png')  (falls die Datei lokal vorhanden ist)

import urllib.request, io
from PIL import Image as PILImage

try:
    url = 'https://sipi.usc.edu/database/preview/misc/4.2.07.png'
    with urllib.request.urlopen(url, timeout=5) as r:
        img = np.array(PILImage.open(io.BytesIO(r.read())).convert('RGB'))
    print('Bild heruntergeladen.')
except Exception:
    try:
        img = plt.imread('peppers.png')
        print('Lokale peppers.png geladen.')
    except FileNotFoundError:
        print('Kein Bild gefunden — synthetisches Testbild wird verwendet.')
        rr, cc = np.meshgrid(np.linspace(0,1,512), np.linspace(0,1,384))
        img = np.stack([
            (np.abs(np.sin(rr*9)) * 255).astype(np.uint8),
            (np.abs(np.cos(cc*7)) * 200).astype(np.uint8),
            ((1-rr) * 180).astype(np.uint8)
        ], axis=2)

# MATLAB: size(img)
print('img.shape :', img.shape)   # (Hoehe, Breite, Kanaele)
print('img.dtype :', img.dtype)


In [ ]:
# MATLAB: imshow(img)
fig, ax = plt.subplots(figsize=(6,5))
ax.imshow(img)
ax.axis('off')
plt.tight_layout()
plt.show()


In [ ]:
# MATLAB: imwrite(img, 'paprikas.jpg')
plt.imsave('paprikas.jpg', img)
print('paprikas.jpg gespeichert.')


---
## Gamut Plot

Das Bild wird in eine Liste von (R,G,B)-Punkten umgewandelt und im 3D-Farbraum geplottet.
So sieht man, welche Farben im Bild tatsächlich vorkommen.

```matlab
% MATLAB:
tmpImg = imresize(img, 0.5);
tmpImg = double(reshape(tmpImg, [], 3));
scatter3(tmpImg(:,1), tmpImg(:,2), tmpImg(:,3), 3, tmpImg/255)
```


In [ ]:
# Bild verkleinern damit nicht Millionen Punkte gezeichnet werden müssen
# MATLAB: tmpImg = imresize(img, 0.5);
tmp_img = img[::2, ::2, :]                        # jede 2. Zeile und Spalte nehmen

# Bild in einen N×3-Vektor umformen
# MATLAB: tmpImg = double(reshape(tmpImg, [], 3));
pts    = tmp_img.reshape(-1, 3).astype(float)     # shape: (N, 3)
colors = pts / 255.0                              # normiert auf 0-1 für matplotlib

fig = plt.figure(figsize=(6,5))
ax  = fig.add_subplot(111, projection='3d')

# MATLAB: scatter3(tmpImg(:,1), tmpImg(:,2), tmpImg(:,3), 3, tmpImg/255)
ax.scatter(pts[:,0], pts[:,1], pts[:,2], c=colors, s=1, alpha=0.4)

ax.set_xlabel('R'); ax.set_ylabel('G'); ax.set_zlabel('B')
ax.set_xlim(0,255); ax.set_ylim(0,255); ax.set_zlim(0,255)
ax.set_title('Gamut Plot — mit der Maus drehen')
plt.tight_layout()
plt.show()


---
## Histogramm

MATLAB: `imhist(img)` — in matplotlib verwenden wir `ax.hist()`.


In [ ]:
# MATLAB: imhist(img)
fig, ax = plt.subplots(figsize=(7,3))

for kanal, farbe, name in [(0,'red','R'), (1,'green','G'), (2,'blue','B')]:
    ax.hist(img[:,:,kanal].ravel(),   # .ravel() macht aus 2D ein 1D-Array
            bins=256, range=(0,255),
            color=farbe, alpha=0.5, label=name)

ax.set_xlabel('Pixelwert (0-255)')
ax.set_ylabel('Anzahl')
ax.set_title('Histogramm')
ax.legend()
plt.tight_layout()
plt.show()


---
## Indizierung — Zeilen, Spalten, Kanäle

Python-Slice-Syntax: `start:stop` — **stop ist ausgeschlossen!**
Ein einzelner `:` bedeutet 'alle Elemente'.

| MATLAB | Python | Bedeutung |
|---|---|---|
| `img(1:80,:,:)` | `img[:80,:,:]` | erste 80 Zeilen |
| `img(end-80:end,:,:)` | `img[-80:,:,:]` | letzte 80 Zeilen |
| `img(:,:,1)` | `img[:,:,0]` | Rotkanal (Index **0**!) |
| `img(:,:,2)` | `img[:,:,1]` | Grünkanal |
| `img(:,:,3)` | `img[:,:,2]` | Blaukanal |


In [ ]:
# MATLAB: imshow( img(1:80, :, :) )
fig, ax = plt.subplots(figsize=(6,2))
ax.imshow(img[:80, :, :])
ax.set_title('Erste 80 Zeilen  —  img[:80, :, :]')
ax.axis('off')
plt.tight_layout()
plt.show()


In [ ]:
# MATLAB: subplot(1,3,1); imshow(img(:,:,1))  usw.
fig, axes = plt.subplots(1, 3, figsize=(10,3))

# Kanal-Index: MATLAB 1,2,3  ->  Python 0,1,2
axes[0].imshow(img[:,:,0], cmap='gray'); axes[0].set_title('Rotkanal');   axes[0].axis('off')
axes[1].imshow(img[:,:,1], cmap='gray'); axes[1].set_title('Gruenkanal'); axes[1].axis('off')
axes[2].imshow(img[:,:,2], cmap='gray'); axes[2].set_title('Blaukanal');  axes[2].axis('off')

plt.tight_layout()
plt.show()


In [ ]:
# MATLAB: imshow( img(end-80:end, :, :) )
# Negative Indizes zaehlen vom Ende — kein 'end' noetig
fig, ax = plt.subplots(figsize=(6,2))
ax.imshow(img[-80:, :, :])
ax.set_title('Letzte 80 Zeilen  —  img[-80:, :, :]')
ax.axis('off')
plt.tight_layout()
plt.show()


## Lesezugriff auf einen Pixel


In [ ]:
# MATLAB: img(240, 100, :)   <- 8-bit Werte fuer R', G', B' (von 0 bis 255)
# Python:  img[239, 99, :]   <- 0-indiziert!
print('R =', img[239, 99, 0],
      ' G =', img[239, 99, 1],
      ' B =', img[239, 99, 2])


## Schreibzugriff auf Pixel


In [ ]:
# MATLAB: tmpImg = img;  tmpImg(240:260, 100:120, :) = 0;
tmp_img = img.copy()              # .copy() ist wichtig! Sonst wird das Original veraendert.
tmp_img[239:260, 99:120, :] = 0  # schwarzes Rechteck einschreiben

fig, ax = plt.subplots(figsize=(6,5))
ax.imshow(tmp_img)
ax.set_title('Schwarzes Rechteck eingeschrieben')
ax.axis('off')
plt.tight_layout()
plt.show()


## Jede zweite Zeile / Schritt-Indizierung

Python-Slices unterstützen einen Schritt: `start:stop:step`.

| MATLAB | Python |
|---|---|
| `1:2:end` | `::2` |
| `10:-1:1` | `9::-1` |


In [ ]:
# MATLAB: tmpImg(1:2:end, 1:2:end, 2) = 255
tmp_img2 = img.copy()
tmp_img2[::2, ::2, 1] = 255   # jeden 2. Pixel, Gruenkanal auf Maximum

fig, ax = plt.subplots(figsize=(6,5))
ax.imshow(tmp_img2)
ax.set_title('Jeden 2. Pixel: Gruenkanal = 255')
ax.axis('off')
plt.tight_layout()
plt.show()


---
## Immer vektorisierten Code schreiben!

Beispiel: **Kontrastfunktion**  $\\text{out} = (\\text{in} - 0.5) \\times \\text{contrast} + 0.5$

Zwei Implementierungen — identisches Ergebnis, sehr unterschiedliche Geschwindigkeit.


In [ ]:
# Zuerst von uint8 (0-255) nach float64 (0-1) konvertieren
# MATLAB: img = double(img) / 255;
img_float = img.astype(np.float64) / 255.0
print('dtype:', img_float.dtype, '  Wertebereich:', img_float.min(), '...', img_float.max())


In [ ]:
contrast = 1.1

# -- For-Schleife ----------------------------------------------------------
# MATLAB:
# for a=1:imgSize(1)
#   for b=1:imgSize(2)
#     for c=1:3
#       imgForLoop(a,b,c) = (img(a,b,c) - 0.5)*contrast + 0.5;

H, W, C = img_float.shape

t0 = time.perf_counter()   # MATLAB: tic

img_for_loop = np.empty_like(img_float)
for a in range(H):
    for b in range(W):
        for c in range(C):
            img_for_loop[a,b,c] = (img_float[a,b,c] - 0.5) * contrast + 0.5

t_loop = time.perf_counter() - t0   # MATLAB: toc
print(f'For-Schleife benoetigt viel Zeit: {t_loop*1000:.0f} ms')


In [ ]:
# -- Vektorisierter Code --------------------------------------------------
# MATLAB: imgVec = (img - 0.5) .* contrast + 0.5;
# In NumPy ist * bereits elementweise — kein Punkt noetig

t0 = time.perf_counter()   # MATLAB: tic

img_vec = (img_float - 0.5) * contrast + 0.5

t_vec = time.perf_counter() - t0
print(f'Vektorisiert geht schneller: {t_vec*1000:.2f} ms')
print(f'Speedup: {t_loop/t_vec:.0f}x')


In [ ]:
# MATLAB: if isequal(imgForLoop, imgVec)
if np.allclose(img_for_loop, img_vec):
    print('Ergebnis ist aber gleich')
else:
    print('Wir haben ein Problem!')


In [ ]:
fig, axes = plt.subplots(1, 2, figsize=(10,4))
axes[0].imshow(np.clip(img_float, 0, 1)); axes[0].set_title('Original');             axes[0].axis('off')
axes[1].imshow(np.clip(img_vec,   0, 1)); axes[1].set_title(f'Kontrast = {contrast}'); axes[1].axis('off')
plt.tight_layout()
plt.show()


---
## Weitere nützliche Funktionen

Für sonstige Bildbearbeitung — Python-Äquivalente der MATLAB-Funktionen:

| MATLAB | Python |
|---|---|
| `imresize(img, 0.5)` | `PILImage.fromarray(img).resize((W//2, H//2))` |
| `imcrop` | `img[y:y+h, x:x+w, :]` |
| `imrotate(img, 90)` | `np.rot90(img)` |
| `imfilter` | `scipy.ndimage.convolve` |
| `fspecial('gaussian',…)` | `scipy.ndimage.gaussian_filter` |
| `reshape(x,[],3)` | `x.reshape(-1, 3)` |
| `repmat(p, r, c)` | `np.tile(p, (r, c))` |


---
## Zusammenfassung — MATLAB -> Python Spickzettel

| MATLAB | Python / NumPy | Hinweis |
|---|---|---|
| `a = 3.14` | `a = 3.14` | identisch |
| `a` ohne `;` | `a` als letzter Ausdruck | identisch |
| `a = x;` (unterdrücken) | `a = x` | Zuweisung ist immer still |
| `[1, 2, 3]` | `np.array([1, 2, 3])` | |
| `[1; 2; 3]` | `np.array([[1],[2],[3]])` | |
| `b'` (transponieren) | `b.reshape(-1,1)` | |
| `m(1,3)` | `m[0,2]` | **0-indiziert!** |
| `m(end,end)` | `m[-1,-1]` | negativ = vom Ende |
| `m.*m` | `m * m` | elementweise (Standard!) |
| `m*m` | `m @ m` | Matrixmultiplikation |
| `m.^2` | `m ** 2` | |
| `eye(3)` | `np.eye(3)` | |
| `uint8(x)` | `np.clip(x,0,255).astype(np.uint8)` | erst clip! |
| `double(img)/255` | `img.astype(np.float64)/255` | |
| `imread('f.png')` | `plt.imread('f.png')` | |
| `imshow(img)` | `ax.imshow(img)` + `plt.show()` | |
| `imwrite(img,'f.jpg')` | `plt.imsave('f.jpg', img)` | |
| `size(img)` | `img.shape` | |
| `img(1:80,:,:)` | `img[:80,:,:]` | stop ausgeschlossen |
| `img(end-80:end,:,:)` | `img[-80:,:,:]` | |
| `img(:,:,1)` | `img[:,:,0]` | **0-indizierte Kanäle!** |
| `1:2:end` | `::2` | Schritt-Slice |
| `reshape(x,[],3)` | `x.reshape(-1,3)` | |
| `tic / toc` | `t=time.perf_counter()` / `time.perf_counter()-t` | |
| `isequal(a,b)` | `np.allclose(a,b)` | toleriert Float-Rundung |
